### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ravinderpalsinghdrish**
t

### CODE REVIEW

**Review by Subhash868 — APPROVED** [review]
ok

**Review by Gaurav91elabs — APPROVED** [review]
ok

**Comment by ravinderpalsinghdrish** [comment]
plz check

**Review by vinver1981 — APPROVED** [review]
ok

**Review by elabsteam2024 — COMMENTED** [review]
check

**Review by elabsteam2024 — COMMENTED** [review]
check

**Pull request merged**
